### ISSUE TITLE
[Question][Example]

### ISSUE THREAD

**Issue by charlescho64** [Wiznet/W7500P#1]
Hi, All

I survey IoT gateway solution with ethernet and I found your solution. 

If you have example project to pull/push data to server, I hope you inform me. Our server is developed with Mysql and php.

BR

**Comment by edwin-oetelaar** [comment]
Hello Charles?

I am a developer from the Netherlands and have implemented MQTT pub/sub directly on the W7500p using the Wiznet chip API not the socket API.
It also runs a webserver and logging to SD card. It uses FreeRTOS for scheduling.
This is not open source code, it is not arduino code and it is not the eclipse code.
This allows me to control remote devices, and accept commands from remote using a mqtt broker like mosquitto.

If you are interested you can contact me for doing business, I can implement clients and server for you.
Another option is that wiznet does business with me so I can release it under an MIT license for everyone.

Greetings.
Edwin van den Oetelaar ( edwin at oetelaar dot com )

**Comment by charlescho64** [comment]
Hello, Edwin 

Thank your response. Your word is very happy to me, but I am so sorry to let you know we have other solution to develop IoT system. 

Any way, I hope your work is very well.

Bye

**Comment by khj098765** [comment]
Hi charlescho64

I don't know about your IoT gateway system.
However, WIZnet offers a variety of examples W7500 series(W7500, W7500P) mbed platform.
Please enter the below links.

https://developer.mbed.org/teams/WIZnet/
https://developer.mbed.org/teams/WIZnet/code/TCPClient_HelloWorld_WIZwiki-W7500/

Thank you!
