### ISSUE TITLE
Bug + Fix, using undefined value in /W7500P_FW/ioLibrary/MDIO/W7500x_miim.c#L60

### ISSUE THREAD

**Issue by edwin-oetelaar** [Wiznet/W7500P#11]
https://github.com/Wiznet/W7500P/blob/master/W7500P_FW/ioLibrary/MDIO/W7500x_miim.c#L60

```
  void mdio_init(GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin_MDC, uint16_t GPIO_Pin_MDIO)
  {
     /* Set GPIOs for MDIO and MDC */
     GPIO_InitTypeDef GPIO_InitDef;  

     GPIO_InitDef.GPIO_Pin = GPIO_Pin_MDC | GPIO_Pin_MDIO;
     GPIO_InitDef.GPIO_Mode = GPIO_Mode_OUT;
     GPIO_Init(GPIOx, &GPIO_InitDef);
```

the GPIO_InitDef structure was not initialised correctly, the  GPIO_Pad bits were RANDOM.

This is how it should be done :

```
  void mdio_init(GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin_MDC, uint16_t GPIO_Pin_MDIO)
  {
     /* Set GPIOs for MDIO and MDC */
     GPIO_InitTypeDef GPIO_InitDef;  
    GPIO_StructInit(&GPIO_InitDef); // init the structure
     GPIO_InitDef.GPIO_Pin = GPIO_Pin_MDC | GPIO_Pin_MDIO;
     GPIO_InitDef.GPIO_Mode = GPIO_Mode_OUT;
     GPIO_Init(GPIOx, &GPIO_InitDef);
```

This could give very unexpected results, since these bits control : 
- pull up / pull down
- low or high drive strength
- buffer enable
- schmitt trigger enable / CMOS enable

Please review your code,
Best regards,
Edwin van den Oetelaar

**Comment by khj098765** [comment]
I fixed this issue. thank you so much :)
