### ISSUE TITLE
W7500x.h Line 189: PWM5LK_PVSR

### ISSUE THREAD

**Issue by arm8686** [Wiznet/W7500P#15]
__IO  uint32_t  PWM5LK_PVSR;        /*!< PWM5CLK prescale value select register,       Address offset : 0x104 */     

should be:

  __IO  uint32_t  PWM5**C**LK_PVSR;        /*!< PWM5CLK prescale value select register,       Address offset : 0x104 */

**Comment by khj098765** [comment]
I could fixed bug by your kindness.
thankyou
