### ISSUE TITLE
bugs in ioLibrary//Internet/DNS/dns.c

### ISSUE THREAD

**Issue by edwin-oetelaar** [Wiznet/W7500P#2]
ioLibrary//Internet/DNS/dns.c line 342

you are using memset with wrong arguments
would need to be

memset(pdhdr, 0, sizeof(_pdhdr)); /_ you need to dereference your pointer */
# ifdef _DNS_DEUBG_

would need to be
# ifdef  _DNS_DEBUG_

Please fix this,
Edwin van den Oetelaar

**Comment by edwin-oetelaar** [comment]
the wrong initialization of memory is still not fixed. (now 18 days ago reported)
Since a license blob was added in the file the problem moved to
https://github.com/Wiznet/W7500P/blob/master/W7500P_FW/ioLibrary/Internet/DNS/dns.c#L355

`memset(pdhdr, 0, sizeof(* pdhdr));`

Who cares? I will just fix it in my own copy.

**Comment by khj098765** [comment]
Sorry... It seems to be missing when I update source code.
but Now I fixed again. 
Thank you
