### ISSUE TITLE
Software copyright license, what is it?

### ISSUE THREAD

**Issue by edwin-oetelaar** [Wiznet/W7500P#4]
The code says :  COPYRIGHT 2015 WIZnet Co.,Ltd.
Does this mean I can use this code in my product?
Can I use it without an additional license in GPL projects or MIT licensed projects?
Is this code freeware?
What does the license imply?

Please tell me if I can use this code in my GPL or MIT or MPL2 licensed project without legal issues later.

**Comment by khj098765** [comment]
Hi edwin
currently this code is freeware.
Can you use it without an additional license in MIT licensed projects... 
but Report your questions and decided to apply the MIT LICENSE.
So... I hope, according to MIT LICENSE
What is your opinion about?? 
We want to resolve this issue through communication.
thank you~!

**Comment by edwin-oetelaar** [comment]
I have trouble understanding the "All rights reserved." in the header with my desire to use your code in my project.
I want to share my project with others, but you have all the rights (it says so in the header)
If you "reserve all rights" does this not imply that I have none?

**Comment by edwin-oetelaar** [comment]
Ok, my conclusion is this.
You are the author of the code, so you have all the rights.
But since you are the author you explicitly grant everyone the right to use and distribute your code under any license they want if they obey with your terms.
Your terms being : 
- You assume NO responsibility (NO liability) whatsoever about this code or its correctness
- Everyone using this code must display your license and not remove it from the code
- Someone using the code can not use the name of the author to endorse the product

So after some searching that looks like a BSD license.

https://opensource.org/licenses/BSD-2-Clause

I am fine with that.

**Comment by edwin-oetelaar** [comment]
It appears a new MIT license-blob has been added to every source file.
MIT is fine, code can be used without issues later.
I will close the issue now.
