### ISSUE TITLE
Bug in W7500P_FW/ioLibrary/Ethernet/socket.c (reading wrong register)

### ISSUE THREAD

**Issue by edwin-oetelaar** [Wiznet/W7500P#5]
There is something not logical in the listen() function.
Reading wrong register for socket status.

```

int8_t listen(uint8_t sn)
{
    CHECK_SOCKNUM();
    CHECK_SOCKMODE(Sn_MR_TCP);
    CHECK_SOCKINIT();
    setSn_CR(sn,Sn_CR_LISTEN); /* send the LISTEN command to the chip */
    while(getSn_CR(sn)); /* spin until chip has accepted command, until register is 0x00 */
    while(getSn_SR(sn) != SOCK_LISTEN)
    {
        if(getSn_CR(sn) == SOCK_CLOSED) 
/* ERROR : reading CONTROL register instead of status register 
for checking status of socket, this is always 0x00, we checked this already */ 
        {
            close(sn);
            return SOCKERR_SOCKCLOSED;
        }
    }
    return SOCK_OK;
}
```

I think **`if(getSn_CR(sn) == SOCK_CLOSED)`** is wrong. 
Maybe it should be **`if(getSn_SR(sn) == SOCK_CLOSED)`** but I let you figure it out.

Best regards,
Edwin van den Oetelaar

**Comment by khj098765** [comment]
Hi edwin~!

Thank you discover an error.
your right!
if(getSn_CR(sn) == SOCK_CLOSED)  is wrong in Listen function
but don't need change if(getSn_SR(sn) == SOCK_CLOSED).
if(getSn_SR(sn) == SOCK_CLOSED) is don't need source code.
Now I fixed~. 

Thank you
