### ISSUE TITLE
Bug + Fix in reading inputs from GPIO : discarding 8 bits

### ISSUE THREAD

**Issue by edwin-oetelaar** [Wiznet/W7500P#6]
There is a problem reading data from GPIO port, the return type is 8 bits wide, but the IO port is 16 bits wide.

master/W7500P_FW/Libraries/W7500x_stdPeriph_Driver/src/W7500x_gpio.c

You discard 8 bits from the input register.

> uint8_t GPIO_ReadInputData(GPIO_TypeDef\* GPIOx)
> {
>     assert_param(IS_GPIO_ALL_PERIPH(GPIOx));
>     return ((uint16_t)GPIOx->DATA);
> }

The return type should be 'uint16_t' not 'uint8_t'

> uint16_t GPIO_ReadInputData(GPIO_TypeDef\* GPIOx)

You also need to fix the header file : inc/W7500x_gpio.h

very strange nobody has caught this bug... or reviews this library.
Best regards,
Edwin van den Oetelaar

**Comment by khj098765** [comment]
I fixed this issue. thank you so much :)
