### ISSUE TITLE
Bug + Fix in W7500x_dualtimer.h

### ISSUE THREAD

**Issue by edwin-oetelaar** [Wiznet/W7500P#7]
at line 42 a typo PREE vs PRE:

> # define IS_DUALTIMER_TimerPre(PREE)         (PRE <= 2)

should read

> # define IS_DUALTIMER_TimerPre(PRE)         (PRE <= 2)

or using USE_FULL_ASSERT will not work

Please review this code

Best regards,
Edwin van den Oetelaar

**Comment by khj098765** [comment]
I fixed this issue. thank you so much :)
