### ISSUE TITLE
Bug + fix in W7500x_gpio.h

### ISSUE THREAD

**Issue by edwin-oetelaar** [Wiznet/W7500P#8]
The macro definition is broken in 
https://github.com/Wiznet/W7500P/blob/master/W7500P_FW/Libraries/W7500x_stdPeriph_Driver/inc/W7500x_gpio.h#L145

> # define IS_PAD_TYPE(Px)  (((Px) == PAD_PA) || ((Px) == PAD_PB) \
> 
> ```
>                       ((Px) == PAD_PC))
> ```

should be 

> # define IS_PAD_TYPE(Px)  ( ((Px) == PAD_PA) || ( (Px) == PAD_PB)  ||  ((Px) == PAD_PC) )

please notice you were missing the '||' 

Please review this code.

Best regards,
Edwin van den Oetelaar

**Comment by khj098765** [comment]
I fixed this issue. thank you so much :)
