### ISSUE TITLE
Bugs in W7500x_stdPeriph_Driver/src/W7500x_pwm.c

### ISSUE THREAD

**Issue by edwin-oetelaar** [Wiznet/W7500P#9]
I will report some bugs, but not all, I do not have the time to fix this library.

Example of problems (copy and paste code)

line 240:

> void PWM_CounterModeInit(PWM_CHn_TypeDef\* PWM_CHn, PWM_CounterModeInitTypeDef\* PWM_CounterModeInitStruct) //complete
> {
>     /\* Check the parameters */
>     assert_param(IS_PWM_ALL_CH(PWM_CHn));
>     assert_param(IS_PWM_PR_FILTER(PWM_TimerModeInitStruct->PWM_CHn_PR));
>     assert_param(IS_PWM_MR_FILTER(PWM_CHn, PWM_TimerModeInitStruct->PWM_CHn_MR));
>     assert_param(IS_PWM_LR_FILTER(PWM_CHn, PWM_TimerModeInitStruct->PWM_CHn_LR));
>     assert_param(IS_PWM_CHn_UDMR(PWM_TimerModeInitStruct->PWM_CHn_UDMR));
>     assert_param(IS_PWM_CHn_PDMR(PWM_TimerModeInitStruct->PWM_CHn_PDMR));
>     assert_param(IS_PWM_CHn_TCMR(PWM_TimerModeInitStruct->PWM_CHn_TCMR));
>     assert_param(IS_PWM_CHn_PEEER(PWM_TimerModeInitStruct->PWM_CHn_PEEER));

The above code references "PWM_TimerModeInitStruct" which should be "PWM_CounterModeInitStruct"

The code does the wrong thing too :

>    /\* Select Timer/Counter mode as Timer mode */ 
>     PWM_CHn->TCMR = PWM_CHn_TCMR_TimerMode;    

The line above sets TIMER instead of COUNTER mode like the name says.
Furthermore it should have used 

> PWM_CHn->TCMR = PWM_CounterModeInitStruct->PWM_CHn_TCMR

instead

> ```
> /* Set Match register value */
> PWM_CHn->MR = PWM_CounterModeInitStruct->PWM_CHn_MR;
> /* Set Limit register value */
> PWM_CHn->LR = PWM_CounterModeInitStruct->PWM_CHn_LR;
> /* Select Up-down mode */
> ```

Please review this code, it contains much more errors, but I have limited time.
Best regards,
Edwin van den Oetelaar

**Comment by hjjeon0608** [comment]
I modified and updated.
